// ============================================================
//  postiiify — POSTERS PRODUCTS
//  Sub-categories: anime, cars, singers
//
//  HOW TO ADD A POSTER:
//  1. Copy one of the blocks below
//  2. Change id (must be unique across ALL product files)
//  3. Fill in name, series, price, subtype, emoji, imgs
//  4. Set inStock: true or false
//
//  subtype options: "anime" | "cars" | "singers"
//  imgs: array of image paths e.g. ["images/poster1.jpg"]
//        leave as [] to use emoji placeholder
// ============================================================

const PRODUCTS_POSTERS = [

  // ── ANIME POSTERS ─────────────────────────────────────────
  {
    id: 3002,
    name: "berserk 4",
    series: "Berserk",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/berserk/berserk 4.jpg"],
  },
  {
    id: 3003,
    name: "berserk guts",
    series: "Berserk",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/berserk/berserk,guts.jpg"],
  },
  {
    id: 3004,
    name: "berserk",
    series: "Berserk",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/berserk/berserk.jpg"],
  },
  {
    id: 3005,
    name: "Berserk3",
    series: "Berserk",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/berserk/Berserk3.jpg"],
  },
  {
    id: 3006,
    name: "guts and takejo2",
    series: "Berserk",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/berserk/guts and takejo2.jpg"],
  },
  {
    id: 3007,
    name: "guts berserk",
    series: "Berserk",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/berserk/guts,berserk.jpg"],
  },
  {
    id: 3008,
    name: "guts2",
    series: "Berserk",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/berserk/guts2.jpg"],
  },
  {
    id: 3009,
    name: "guts3",
    series: "Berserk",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/berserk/guts3.jpg"],
  },
  {
    id: 3010,
    name: "noritoshi jjk",
    series: "Berserk",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/berserk/noritoshi,jjk.jpg"],
  },
  {
    id: 3011,
    name: "takejo and guts",
    series: "Berserk",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/berserk/takejo and guts.jpg"],
  },
  {
    id: 3012,
    name: "batman",
    series: "DC Comics",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "dc",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/dc/batman.jpg"],
  },
  {
    id: 3013,
    name: "Demon Slayer│Kimetsu no Yaiba",
    series: "Demon Slayer",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/demon slayer/Demon Slayer│Kimetsu no Yaiba.jpg"],
  },
  {
    id: 3014,
    name: "kokoushibo demon slayer",
    series: "Demon Slayer",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/demon slayer/kokoushibo,demon slayer.jpg"],
  },
  {
    id: 3015,
    name: "Kokushibo demon slayer",
    series: "Demon Slayer",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/demon slayer/Kokushibo,demon slayer.jpg"],
  },
  {
    id: 3016,
    name: "sanemi demon slayer",
    series: "Demon Slayer",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/demon slayer/sanemi,demon slayer.jpg"],
  },
  {
    id: 3017,
    name: "tanjiro demon slayer",
    series: "Demon Slayer",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/demon slayer/tanjiro,demon slayer.jpg"],
  },
  {
    id: 3018,
    name: "Zenitsu Wallpaper",
    series: "Demon Slayer",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/demon slayer/Zenitsu Wallpaper.jpg"],
  },
  {
    id: 3019,
    name: "zenitsu demon slayer",
    series: "Demon Slayer",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/demon slayer/zenitsu,demon slayer.jpg"],
  },
  {
    id: 3020,
    name: "zenitsu",
    series: "Demon Slayer",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/demon slayer/zenitsu.jpg"],
  },
  {
    id: 3021,
    name: "hell paradise 2",
    series: "Hell Paradise",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/hell paradise/hell paradise 2.jpg"],
  },
  {
    id: 3022,
    name: "hell paradise 4",
    series: "Hell Paradise",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/hell paradise/hell paradise 4.jpg"],
  },
  {
    id: 3023,
    name: "hell paradise 5",
    series: "Hell Paradise",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/hell paradise/hell paradise 5.jpg"],
  },
  {
    id: 3024,
    name: "hell paradise",
    series: "Hell Paradise",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/hell paradise/hell paradise.jpg"],
  },
  {
    id: 3025,
    name: "Shion hells paradaise 5",
    series: "Hell Paradise",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/hell paradise/Shion hells paradaise 5.jpg"],
  },
  {
    id: 3026,
    name: "Choso jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/Choso ,jjk.jpg"],
  },
  {
    id: 3027,
    name: "fushiguro and maharaga",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/fushiguro and maharaga.jpg"],
  },
  {
    id: 3028,
    name: "fushiguro toji",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/fushiguro toji.jpg"],
  },
  {
    id: 3029,
    name: "geto jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/geto,jjk.jpg"],
  },
  {
    id: 3030,
    name: "Gojo Satoru 3",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/Gojo Satoru 3.jpg"],
  },
  {
    id: 3031,
    name: "gojo saturo and ryomen sukuna jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/gojo saturo and ryomen sukuna,jjk.jpg"],
  },
  {
    id: 3032,
    name: "gojo saturo jjk 2",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/gojo saturo,jjk 2.jpg"],
  },
  {
    id: 3033,
    name: "gojo saturo jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/gojo saturo,jjk.jpg"],
  },
  {
    id: 3034,
    name: "gojo jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/gojo,jjk.jpg"],
  },
  {
    id: 3035,
    name: "Kinji Hakari and Kirara Hoshi jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/Kinji Hakari and Kirara Hoshi,jjk.jpg"],
  },
  {
    id: 3036,
    name: "kokoushibo",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/kokoushibo.jpg"],
  },
  {
    id: 3037,
    name: "MAHORAGA 3",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/MAHORAGA 3.jpg"],
  },
  {
    id: 3038,
    name: "noritoshi 2 jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/noritoshi 2,jjk.jpg"],
  },
  {
    id: 3039,
    name: "noritoshi 3 jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/noritoshi 3,jjk.jpg"],
  },
  {
    id: 3040,
    name: "noritoshi jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/noritoshi,jjk.jpg"],
  },
  {
    id: 3041,
    name: "Sukuna Mahoraga jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/Sukuna Mahoraga ,jjk.jpg"],
  },
  {
    id: 3042,
    name: "Sukuna jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/Sukuna,jjk.jpg"],
  },
  {
    id: 3043,
    name: "toji",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/toji.jpg"],
  },
  {
    id: 3044,
    name: "yuta 2 jjk",
    series: "Jujutsu Kaisen",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/jjk/yuta 2,jjk.jpg"],
  },
  {
    id: 3045,
    name: "lord krishan 3",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishan 3.jpg"],
  },
  {
    id: 3046,
    name: "lord krishna 10",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishna 10.jpg"],
  },
  {
    id: 3047,
    name: "lord krishna 11",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishna 11.jpg"],
  },
  {
    id: 3048,
    name: "lord krishna 12",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishna 12.jpg"],
  },
  {
    id: 3049,
    name: "lord krishna 2",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishna 2.jpg"],
  },
  {
    id: 3050,
    name: "lord krishna 4",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishna 4.jpg"],
  },
  {
    id: 3051,
    name: "lord krishna 5",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishna 5.jpg"],
  },
  {
    id: 3052,
    name: "lord krishna 6",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishna 6.jpg"],
  },
  {
    id: 3053,
    name: "lord krishna 7",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishna 7.jpg"],
  },
  {
    id: 3054,
    name: "lord krishna 8",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishna 8.jpg"],
  },
  {
    id: 3055,
    name: "lord krishna 9",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishna 9.jpg"],
  },
  {
    id: 3056,
    name: "lord krishna",
    series: "Lord Krishna",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "god",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/lord krishna/lord krishna.jpg"],
  },
  {
    id: 3057,
    name: "spiderman",
    series: "Marvel",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "marvel",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/marvel/spiderman.jpg"],
  },
  {
    id: 3058,
    name: "deku my hero academia",
    series: "My Hero Academia",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/mha/deku,my hero academia.jpg"],
  },
  {
    id: 3059,
    name: "luffy 2 one piece",
    series: "One Piece",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/one piece/luffy 2 ,one piece.jpg"],
  },
  {
    id: 3060,
    name: "bang 2 opm",
    series: "One Punch Man",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/one punch man/bang 2,opm.jpg"],
  },
  {
    id: 3061,
    name: "bang opm",
    series: "One Punch Man",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/one punch man/bang,opm.jpg"],
  },
  {
    id: 3062,
    name: "garou 2 opm",
    series: "One Punch Man",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/one punch man/garou 2,opm.jpg"],
  },
  {
    id: 3063,
    name: "garou 3 opm",
    series: "One Punch Man",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/one punch man/garou 3,opm.jpg"],
  },
  {
    id: 3064,
    name: "Garou Body opm",
    series: "One Punch Man",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/one punch man/Garou Body , opm.jpg"],
  },
  {
    id: 3065,
    name: "garou opm",
    series: "One Punch Man",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/one punch man/garou,opm.jpg"],
  },
  {
    id: 3066,
    name: "saitama opm",
    series: "One Punch Man",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/one punch man/saitama,opm.jpg"],
  },
  {
    id: 3067,
    name: "takejo 1 vegabond",
    series: "Vagabond",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/vwgabond/takejo 1,vegabond.jpg"],
  },
  {
    id: 3068,
    name: "takejo 1",
    series: "Vagabond",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/vwgabond/takejo 1.jpg"],
  },
  {
    id: 3069,
    name: "takejo 3 vegabond",
    series: "Vagabond",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/vwgabond/takejo 3 ,vegabond.jpg"],
  },
  {
    id: 3070,
    name: "takejo 4 vegabond",
    series: "Vagabond",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/vwgabond/takejo 4,vegabond.jpg"],
  },
  {
    id: 3071,
    name: "takejo and guts",
    series: "Vagabond",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/vwgabond/takejo and guts.jpg"],
  },
  {
    id: 3072,
    name: "takejo vegabond",
    series: "Vagabond",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "anime",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/vwgabond/takejo,vegabond.jpg"],
  },
  {
    id: 3073,
    name: "weekend 10",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 10.jpg"],
  },
  {
    id: 3074,
    name: "weekend 11",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 11.jpg"],
  },
  {
    id: 3075,
    name: "weekend 12",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 12.jpg"],
  },
  {
    id: 3076,
    name: "weekend 13",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 13.jpg"],
  },
  {
    id: 3077,
    name: "weekend 14",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 14.jpg"],
  },
  {
    id: 3078,
    name: "weekend 15",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 15.jpg"],
  },
  {
    id: 3079,
    name: "weekend 16",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 16.jpg"],
  },
  {
    id: 3080,
    name: "weekend 17",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 17.jpg"],
  },
  {
    id: 3081,
    name: "weekend 18",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 18.jpg"],
  },
  {
    id: 3082,
    name: "weekend 19",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 19.jpg"],
  },
  {
    id: 3083,
    name: "weekend 2",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 2.jpg"],
  },
  {
    id: 3084,
    name: "weekend 20",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 20.jpg"],
  },
  {
    id: 3085,
    name: "weekend 3",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 3.jpg"],
  },
  {
    id: 3086,
    name: "weekend 4",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 4.jpg"],
  },
  {
    id: 3087,
    name: "weekend 5",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 5.jpg"],
  },
  {
    id: 3088,
    name: "weekend 6",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 6.jpg"],
  },
  {
    id: 3089,
    name: "weekend 7",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 7.jpg"],
  },
  {
    id: 3090,
    name: "weekend 8",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend 8.jpg"],
  },
  {
    id: 3091,
    name: "THE EYES",
    series: "Chico",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/They never lie.jpg"],
  },
  {
    id: 3092,
    name: "weekend",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekend.jpg"],
  },
  {
    id: 3093,
    name: "weekennd 20",
    series: "Weekend",
    oldPrice: 49,
    price: 44,
    type: "poster",
    subtype: "singers",
    inStock: true,
    emoji: "🖼️",
    imgs: ["posters/weekend/weekennd 20.jpg"],
  },
];
