// ============================================================
//  postiiify — ANIME FIGURES PRODUCTS
//
//  HOW TO ADD A FIGURE:
//  1. Copy one of the blocks below
//  2. Change id (must be unique across ALL product files)
//  3. Fill in name, series (include size e.g. "| 18cm"), price, emoji, imgs
//  4. Set inStock: true or false
//
//  imgs: array of image paths e.g. ["anime_figures/figure1.jpg"]
//        leave as [] to use emoji placeholder
// ============================================================
//id 1501 - 3000
const PRODUCTS_FIGURES = [
  {
    id: 1501,
    name: "Akaza 30cm",
    series: "Demon Slayer",
    price: 899,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Akaza 30cm (1photo).jpg', 'anime_figures/Akaza 30cm (2photo).jpg', 'anime_figures/Akaza 30cm (3photo).jpg'],
  },
  {
    id: 1503,
    name: "Beerus 30cm",
    series: "Dragon Ball",
    price: 699,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Beerus 30cm  (1photo).jpg', 'anime_figures/Beerus 30cm  (2photo).jpg', 'anime_figures/Beerus 30cm  (3photo).jpg'],
  },
  {
    id: 1504,
    name: "Giyu Tomioka 15cm",
    series: "Demon Slayer",
    price: 249,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Giyu Tomioka 15cm  (1photo).jpg', 'anime_figures/Giyu Tomioka 15cm  (2photo).jpg'],
  },
  {
    id: 1506,
    name: "Goku 28cm",
    series: "Dragon Ball",
    price: 1099,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Goku 28cm  (1photo).jpg', 'anime_figures/Goku 28cm  (2photo).jpg', 'anime_figures/Goku 28cm  (3photo).jpg'],
  },
  {
    id: 1507,
    name: "Inosuke Hashibira 15cm",
    series: "Demon Slayer",
    price: 249,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Inosuke Hashibira 15cm  (1photo).jpg', 'anime_figures/Inosuke Hashibira 15cm  (2photo).jpg'],
  },
  {
    id: 1508,
    name: "Kimetsu No Yaiba 15cm",
    series: "Demon Slayer",
    price: 249,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Kimetsu no Yaiba 15cm  (1photo).jpg', 'anime_figures/Kimetsu no Yaiba 15cm  (2photo).jpg'],
  },
  {
    id: 1509,
    name: "Monkey D. Luffy Blue Flame 24cm",
    series: "One Piece",
    label: "1 LEFT",
    price: 799,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Monkey D. Luffy blue flame 24cm  (1photo).jpg', 'anime_figures/Monkey D. Luffy blue flame 24cm  (2photo).jpg', 'anime_figures/Monkey D. Luffy blue flame 24cm  (3photo).jpg'],
  },
  {
    id: 1510,
    name: "Monkey D. Luffy Gear 5 18cm",
    series: "One Piece",
    price: 725,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Monkey D. Luffy gear 5 18cm  (1photo).jpg', 'anime_figures/Monkey D. Luffy gear 5 18cm  (2photo).jpg', 'anime_figures/Monkey D. Luffy gear 5 18cm  (3photo).jpg', 'anime_figures/Monkey D. Luffy gear 5 18cm  (4photo).jpg'],
  },
  {
    id: 1511,
    name: "Nzuko Kamado 15cm",
    series: "Demon Slayer",
    price: 249,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Nzuko Kamado 15cm  (1photo).jpg', 'anime_figures/Nzuko Kamado 15cm  (2photo).jpg'],
  },
  {
    id: 1512,
    name: "Roronoa Zoro 28cm",
    series: "One Piece",
    price: 749,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Roronoa Zoro 28cm  (1photo).jpg', 'anime_figures/Roronoa Zoro 28cm  (2photo).jpg', 'anime_figures/Roronoa Zoro 28cm  (3photo).jpg'],
  },
  {
    id: 1513,
    name: "Tanjiro Kamado 15cm",
    series: "Demon Slayer",
    price: 249,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Tanjiro kamado 15cm  (1photo).png']
  },
  {
    id: 1514,
    name: "Tengen Uzui 30cm",
    series: "Demon Slayer",
    price: 899,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Tengen Uzui 30cm  (1photo).jpg', 'anime_figures/Tengen Uzui 30cm  (2photo).jpg', 'anime_figures/Tengen Uzui 30cm  (3photo).jpg'],
  },
  {
    id: 1516,
    name: "Yoriichi Tsugikuni 30cm",
    series: "Demon Slayer",
    price: 899,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Yoriichi Tsugikuni 30cm  (1photo).jpg', 'anime_figures/Yoriichi Tsugikuni 30cm  (2photo).jpg', 'anime_figures/Yoriichi Tsugikuni 30cm  (3photo).jpg', 'anime_figures/Yoriichi Tsugikuni 30cm  (4photo).jpg'],
  },
  {
    id: 1517,
    name: "Zenitsu Agatsuma 15cm",
    series: "Demon Slayer",
    price: 249,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/Zenitsu Agatsuma 15cm  (1photo).png', 'anime_figures/Zenitsu Agatsuma 15cm  (2photo).jpg'],
  },
  {
    id: 1518,
    name: "8 Majin Buu",
    series: "Dragon Ball",
    price: 549,
    type: "figure",
    inStock: true,
    emoji: "🧸",
    imgs: ['anime_figures/8 majin buu (1photo).jpg', 'anime_figures/Ebil Buu (4photo).jpg', 'anime_figures/Kid Buu (3photo).jpg', 'anime_figures/Majin Buu (2photo).jpg', 'anime_figures/second kid buu form (6).jpg', 'anime_figures/Supper Buu (5photo).jpg','anime_figures/Bandai hg (8photo).jpg','anime_figures/vs ultimate gohan (9photo).jpg','anime_figures/Gohan absorbed (7photo).jpg'],
  },
];
